//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public int PacientId { get; set; }
        public string RecordHeader { get; set; }
        public string RecordText { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime RecordDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
