//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempertureList
    {
        public int TempertureListId { get; set; }
        public string TempertureListData { get; set; }
        public int TempertureListPatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
