//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public int TicketHistoryId { get; set; }
        public int TicketHistoryPatientId { get; set; }
        public System.DateTime TicketHistoryDate { get; set; }
        public int TicketHistoryDoctorId { get; set; }
        public int TicketHistoryRoomId { get; set; }
        public Nullable<System.DateTime> TicketHistoryFinishDate { get; set; }
        public string TicketHistoryStatusId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Room Room { get; set; }
        public virtual Status Status { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
